### ISSUE TITLE
How do I apply?

### ISSUE THREAD

**Issue by davidnagli** [HackIllinois/site-2018#49]
Based on the repo I can see that there is a `/auth` route, but I spent a ton of time googling and looking around the site but haven’t been able to find a link to the hackathon application for 2018.

Are applications not open yet? Did they already close? Is this just a bug?

Regardless you guys should probably add something to the page that tells the user :)

**Comment by YashoSharma** [comment]
Hey David, 

We're currently working on writing out the next phase of our website which includes the application page, which should open up shortly in the next few weeks. The auth stuff ended up being written earlier than the application as it was necessary for authentication on native apps as well.

Thanks,

Yash
